name: Keep Workflows Alive

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Keep Alive Script
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_ACTIONS }}
        run: |
          python gh_actions/keep_alive.py

      # This workflow cannot reenable itself. So we add a dummy empty commit so that we
      # keep the repo active and the workflow enabled.
      - name: Keep-Alive Repo Heartbeat
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -B keep-alive-heartbeat
          git commit --allow-empty -m "chore: keep-alive heartbeat"
          git push origin keep-alive-heartbeat --force
